#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env_kilos = env.Clone()
env_kilos.add_source_files(env.modules_sources, "*.cpp")

env_kilos.GLSL_HEADER("shaders/integration.glsl")
env_kilos.GLSL_HEADER("shaders/body_to_multimesh.glsl")
env_kilos.GLSL_HEADER("shaders/pbd_solve.glsl")
env_kilos.GLSL_HEADER("shaders/pbd_finalize.glsl")
env_kilos.GLSL_HEADER("shaders/grid_build.glsl")
env_kilos.GLSL_HEADER("shaders/broad_phase.glsl")
env_kilos.GLSL_HEADER("shaders/narrow_phase.glsl")
env_kilos.GLSL_HEADER("shaders/solver.glsl")
